name: flutter_scan_bluetooth_example
description: Demonstrates how to use the flutter_scan_bluetooth plugin.



version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  datetime_picker_formfield: ^1.0.0

  syncfusion_flutter_calendar: ^18.3.44 
  flutter_local_notifications: ^1.4.4+2
  rxdart: ^0.24.1
  path_provider: ^1.6.11
  http: ^0.12.1
  localstorage: ^3.0.0
  shared_preferences: any
  rflutter_alert: ^1.1.0
  after_layout: ^1.0.7+2
  cupertino_icons: ^0.1.3
  nearby_connections: ^1.0.3
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  modal_progress_hud: ^0.1.3
  location: ^3.0.2
  firebase_messaging:
  firebase_analytics:
  
  flutter_blue:
    
  flutter:
    sdk: flutter
  font_awesome_flutter: '>= 8.8.1'


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  


  


  table_calendar: ^2.0.1
  json_annotation: ^3.0.1
  charts_flutter: ^0.9.0
  intl: ^0.16.1
  google_maps_flutter: ^0.5.24+1
  google_maps: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_scan_bluetooth:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - lib/assets/bkg.png
   - lib/assets/twoleaves.png
   - lib/assets/Eucalyptus.jpg
   - lib/assets/row-1-col-1.jpg
   - lib/assets/row-1-col-2.jpg
   - lib/assets/illustration.png
   - lib/assets/illustration2.jpg
   - lib/assets/illustration3.png
   - lib/assets/flower.jpg
   - lib/assets/bud.jpg
   - lib/assets/Capture.png
   - lib/assets/tenor.gif
   - lib/assets/user.png

  fonts:
    - family: Avenir
      fonts:
        - asset: lib/assets/Avenir-Black.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
